In [53]:
#create a malware detection ai model for a web application, starting from importing the necessary python libraries
import pandas as pd
malware_dataset1 = pd.read_csv("data.csv")
malware_dataset2 = pd.read_csv("dataset.csv")
malware_dataset3 = pd.read_csv("LargeTrain.csv")
malware_dataset4 = pd.read_csv("train_vec.csv")
label_dataset = pd.read_csv("trainLabels.csv")
label_dataset1 = pd.read_csv("trainLabels_bal.csv")

In [54]:
train_data = pd.concat([malware_dataset1, malware_dataset2, malware_dataset3, malware_dataset4, label_dataset, label_dataset1], axis=0)
train_data.head

<bound method NDFrame.head of       asm_commands_add  asm_commands_call  asm_commands_cdq  asm_commands_cld  \
0                436.0              646.0               0.0              10.0
1                469.0              262.0               0.0               4.0
2               1587.0             1828.0               0.0               0.0
3                213.0              227.0               0.0               0.0
4                 36.0               76.0               0.0               0.0
...                ...                ...               ...               ...
1637               NaN                NaN               NaN               NaN
1638               NaN                NaN               NaN               NaN
1639               NaN                NaN               NaN               NaN
1640               NaN                NaN               NaN               NaN
1641               NaN                NaN               NaN               NaN

      asm_commands_cli  asm_commands_cmc  asm_commands_cmp  asm_commands_cwd  \
0                  9.0               0.0             228.0               0.0
1                  1.0               4.0             185.0               4.0
2                 31.0               0.0             689.0               0.0
3                  3.0               0.0             127.0               0.0
4                  0.0               0.0              15.0               0.0
...                ...               ...               ...               ...
1637               NaN               NaN               NaN               NaN
1638               NaN               NaN               NaN               NaN
1639               NaN               NaN               NaN               NaN
1640               NaN               NaN               NaN               NaN
1641               NaN               NaN               NaN               NaN

      asm_commands_daa  asm_commands_dd  ...  f6  f7  f8  f9  fa  fb  fc  fd  \
0                 56.0          89930.0  ... NaN NaN NaN NaN NaN NaN NaN NaN
1                 20.0           3464.0  ... NaN NaN NaN NaN NaN NaN NaN NaN
2                904.0          24833.0  ... NaN NaN NaN NaN NaN NaN NaN NaN
3                132.0          71979.0  ... NaN NaN NaN NaN NaN NaN NaN NaN
4                  0.0            112.0  ... NaN NaN NaN NaN NaN NaN NaN NaN
...                ...              ...  ...  ..  ..  ..  ..  ..  ..  ..  ..
1637               NaN              NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN
1638               NaN              NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN
1639               NaN              NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN
1640               NaN              NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN
1641               NaN              NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN

      fe  ff
0    NaN NaN
1    NaN NaN
2    NaN NaN
3    NaN NaN
4    NaN NaN
...   ..  ..
1637 NaN NaN
1638 NaN NaN
1639 NaN NaN
1640 NaN NaN
1641 NaN NaN

[37669 rows x 2082 columns]>

In [55]:
# Check for missing values in the dataset
missing_values = train_data.isnull().sum()
print(missing_values)

asm_commands_add     15933
asm_commands_call    15933
asm_commands_cdq     15933
asm_commands_cld     15933
asm_commands_cli     15933
                     ...
fb                   36027
fc                   36027
fd                   36027
fe                   36027
ff                   36027
Length: 2082, dtype: int64

In [56]:
# Impute missing values with mean
mean_value = train_data['asm_commands_call'].mean()
train_data['asm_commands_call'].fillna(mean_value, inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_1428\777124974.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_data['asm_commands_call'].fillna(mean_value, inplace=True)

In [57]:
train_data.dtypes

asm_commands_add     float64
asm_commands_call    float64
asm_commands_cdq     float64
asm_commands_cld     float64
asm_commands_cli     float64
                      ...
fb                   float64
fc                   float64
fd                   float64
fe                   float64
ff                   float64
Length: 2082, dtype: object

In [58]:
# Iterate through each column in the DataFrame
for column in train_data.columns:
    # Attempt to convert non-numeric data to numeric, coerce errors
    train_data[column] = pd.to_numeric(train_data[column], errors='coerce')

# Now, all columns will contain numeric data where possible, with non-convertible values replaced by NaN

In [59]:
train_data.dtypes

asm_commands_add     float64
asm_commands_call    float64
asm_commands_cdq     float64
asm_commands_cld     float64
asm_commands_cli     float64
                      ...
fb                   float64
fc                   float64
fd                   float64
fe                   float64
ff                   float64
Length: 2082, dtype: object

In [60]:
# Impute missing values with mean for all columns
mean_values = train_data.mean()
train_data.fillna(mean_values, inplace=True)

In [61]:
# Impute missing values with a constant value for all columns
constant_value = 0  # Define the constant value
train_data.fillna(constant_value, inplace=True)

In [62]:
# Check for missing values in the dataset
missing_values = train_data.isnull().sum()
print(missing_values)

asm_commands_add     0
asm_commands_call    0
asm_commands_cdq     0
asm_commands_cld     0
asm_commands_cli     0
                    ..
fb                   0
fc                   0
fd                   0
fe                   0
ff                   0
Length: 2082, dtype: int64

In [63]:
train_data

,asm_commands_add,asm_commands_call,asm_commands_cdq,asm_commands_cld,asm_commands_cli,asm_commands_cmc,asm_commands_cmp,asm_commands_cwd,asm_commands_daa,asm_commands_dd,...,f6,f7,f8,f9,fa,fb,fc,fd,fe,ff
0,436.000000,646.000000,0.000000,10.000000,9.000000,0.000000,228.000000,0.000000,56.000000,89930.000000,...,1272.193666,1937.803898,2037.507917,1279.190621,1489.5743,1398.861754,2192.052984,1547.922655,2156.564555,12593.462241
1,469.000000,262.000000,0.000000,4.000000,1.000000,4.000000,185.000000,4.000000,20.000000,3464.000000,...,1272.193666,1937.803898,2037.507917,1279.190621,1489.5743,1398.861754,2192.052984,1547.922655,2156.564555,12593.462241
2,1587.000000,1828.000000,0.000000,0.000000,31.000000,0.000000,689.000000,0.000000,904.000000,24833.000000,...,1272.193666,1937.803898,2037.507917,1279.190621,1489.5743,1398.861754,2192.052984,1547.922655,2156.564555,12593.462241
3,213.000000,227.000000,0.000000,0.000000,3.000000,0.000000,127.000000,0.000000,132.000000,71979.000000,...,1272.193666,1937.803898,2037.507917,1279.190621,1489.5743,1398.861754,2192.052984,1547.922655,2156.564555,12593.462241
4,36.000000,76.000000,0.000000,0.000000,0.000000,0.000000,15.000000,0.000000,0.000000,112.000000,...,1272.193666,1937.803898,2037.507917,1279.190621,1489.5743,1398.861754,2192.052984,1547.922655,2156.564555,12593.462241
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1637,724.463839,958.675377,10.774384,200.203165,16.794258,1.900074,480.152742,1.411115,221.034321,16995.688167,...,1272.193666,1937.803898,2037.507917,1279.190621,1489.5743,1398.861754,2192.052984,1547.922655,2156.564555,12593.462241
1638,724.463839,958.675377,10.774384,200.203165,16.794258,1.900074,480.152742,1.411115,221.034321,16995.688167,...,1272.193666,1937.803898,2037.507917,1279.190621,1489.5743,1398.861754,2192.052984,1547.922655,2156.564555,12593.462241
1639,724.463839,958.675377,10.774384,200.203165,16.794258,1.900074,480.152742,1.411115,221.034321,16995.688167,...,1272.193666,1937.803898,2037.507917,1279.190621,1489.5743,1398.861754,2192.052984,1547.922655,2156.564555,12593.462241
1640,724.463839,958.675377,10.774384,200.203165,16.794258,1.900074,480.152742,1.411115,221.034321,16995.688167,...,1272.193666,1937.803898,2037.507917,1279.190621,1489.5743,1398.861754,2192.052984,1547.922655,2156.564555,12593.462241
1641,724.463839,958.675377,10.774384,200.203165,16.794258,1.900074,480.152742,1.411115,221.034321,16995.688167,...,1272.193666,1937.803898,2037.507917,1279.190621,1489.5743,1398.861754,2192.052984,1547.922655,2156.564555,12593.462241

In [64]:
train_data.drop_duplicates(inplace=True)
train_data.reset_index(drop=True, inplace=True)
train_data.dropna(inplace=True)

In [65]:
x_train = train_data.drop(columns=['asm_commands_add'])
y_train = train_data['asm_commands_call']

In [66]:
malware_test1 = pd.read_csv('LargeTest.csv')
malware_test2 = pd.read_csv('sorted_test_id.csv')
malware_test3 = pd.read_csv('test_vec.csv')

In [67]:
test_data = pd.concat([malware_test1, malware_test2, malware_test3], axis=0)
test_data.head

<bound method NDFrame.head of        Virtual  Offset    loc  Import  Imports    var  Forwarder  UINT  LONG  \
0         10.0    10.0  137.0    18.0      6.0   90.0        6.0  27.0   0.0
1          9.0     9.0  108.0    12.0      4.0  135.0        4.0  17.0   2.0
2         11.0    11.0   73.0    21.0      7.0  155.0        7.0  53.0   4.0
3          3.0     3.0   78.0     0.0     12.0  133.0        0.0  60.0   3.0
4          3.0     3.0   37.0    12.0      4.0   44.0        4.0   3.0   0.0
...        ...     ...    ...     ...      ...    ...        ...   ...   ...
10868      NaN     NaN    NaN     NaN      NaN    NaN        NaN   NaN   NaN
10869      NaN     NaN    NaN     NaN      NaN    NaN        NaN   NaN   NaN
10870      NaN     NaN    NaN     NaN      NaN    NaN        NaN   NaN   NaN
10871      NaN     NaN    NaN     NaN      NaN    NaN        NaN   NaN   NaN
10872      NaN     NaN    NaN     NaN      NaN    NaN        NaN   NaN   NaN

        BOOL  ...      f6      f7       f8      f9      fa      fb       fc  \
0       31.0  ...     NaN     NaN      NaN     NaN     NaN     NaN      NaN
1       39.0  ...     NaN     NaN      NaN     NaN     NaN     NaN      NaN
2       67.0  ...     NaN     NaN      NaN     NaN     NaN     NaN      NaN
3      117.0  ...     NaN     NaN      NaN     NaN     NaN     NaN      NaN
4       14.0  ...     NaN     NaN      NaN     NaN     NaN     NaN      NaN
...      ...  ...     ...     ...      ...     ...     ...     ...      ...
10868    NaN  ...  4109.0  2906.0   5249.0  2535.0  2179.0  2641.0   8174.0
10869    NaN  ...  3203.0  3126.0   3254.0  3124.0  3144.0  3292.0   3169.0
10870    NaN  ...  3069.0  3036.0   3102.0  3125.0  3076.0  3121.0   3100.0
10871    NaN  ...   285.0   291.0   6633.0   251.0   125.0   257.0   7076.0
10872    NaN  ...   368.0   341.0  10996.0   215.0   270.0   240.0  17461.0

           fd       fe       ff
0         NaN      NaN      NaN
1         NaN      NaN      NaN
2         NaN      NaN      NaN
3         NaN      NaN      NaN
4         NaN      NaN      NaN
...       ...      ...      ...
10868  2773.0   3667.0  66879.0
10869  3222.0   3249.0   7112.0
10870  3001.0   3175.0   5103.0
10871   772.0   8713.0  45641.0
10872   335.0  11951.0  45481.0

[32619 rows x 2060 columns]>

In [68]:
# Iterate through each column in the DataFrame
for column in test_data.columns:
    # Attempt to convert non-numeric data to numeric, coerce errors
    test_data[column] = pd.to_numeric(test_data[column], errors='coerce')

# Now, all columns will contain numeric data where possible, with non-convertible values replaced by NaN

In [69]:
# Impute missing values with a constant value for all columns
constant_value = 0  # Define the constant value
test_data.fillna(constant_value, inplace=True)

In [70]:
# Check for missing values in the dataset
missing_values = test_data.isnull().sum()
print(missing_values)

Virtual    0
Offset     0
loc        0
Import     0
Imports    0
          ..
fb         0
fc         0
fd         0
fe         0
ff         0
Length: 2060, dtype: int64

In [71]:
test_data

,Virtual,Offset,loc,Import,Imports,var,Forwarder,UINT,LONG,BOOL,...,f6,f7,f8,f9,fa,fb,fc,fd,fe,ff
0,10.0,10.0,137.0,18.0,6.0,90.0,6.0,27.0,0.0,31.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,9.0,9.0,108.0,12.0,4.0,135.0,4.0,17.0,2.0,39.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,11.0,11.0,73.0,21.0,7.0,155.0,7.0,53.0,4.0,67.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3.0,3.0,78.0,0.0,12.0,133.0,0.0,60.0,3.0,117.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3.0,3.0,37.0,12.0,4.0,44.0,4.0,3.0,0.0,14.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10868,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4109.0,2906.0,5249.0,2535.0,2179.0,2641.0,8174.0,2773.0,3667.0,66879.0
10869,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3203.0,3126.0,3254.0,3124.0,3144.0,3292.0,3169.0,3222.0,3249.0,7112.0
10870,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3069.0,3036.0,3102.0,3125.0,3076.0,3121.0,3100.0,3001.0,3175.0,5103.0
10871,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,285.0,291.0,6633.0,251.0,125.0,257.0,7076.0,772.0,8713.0,45641.0
10872,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,368.0,341.0,10996.0,215.0,270.0,240.0,17461.0,335.0,11951.0,45481.0

In [72]:
test_data.drop_duplicates(inplace=True)
test_data.reset_index(drop=True, inplace=True)
test_data.dropna(inplace=True)

In [73]:
x_test = test_data.drop(columns=['ent_q_diff_block_0_18'])
y_test = test_data['INTERNET_STATUS_CALLBACK']

In [78]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Assuming you have already separated your features and labels into x_train and y_train for training
# Assuming you also have x_test and y_test for testing

# Initialize the Random Forest regressor
rf_regressor = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the regressor
rf_regressor.fit(x_train, y_train)

# Predict on the test set
y_pred = rf_regressor.predict(x_test)

# Evaluate the regressor
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R^2 Score:", r2)

MemoryError: Unable to allocate 198. MiB for an array with shape (24957, 2081) and data type float32

In [ ]:
#DEPLOYING TO GIT